apiVersion: app/v1
kind: Deployment
metedata:
  name: nginx-deployment
  label:
    app: nginx
spec:
  replica: 3
  selector:
    matchLabel: 
      app: nginx
template:
  metadata:
    labels:
      app: nginx
  spec:
    containers:
    - name: nginx
      image: nginx:1.2.3
      ports:
      - containerPort: 80 